spring:
  application:
    name: dev-store-api

  profiles:
    active: dev

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.1.14:3306/dev_login}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  docker:
    compose:
      enabled: false
server:
  port: ${SERVER_PORT:8080}

swagger:
  openapi:
    server:
      url: "http://192.168.1.14:${server.port}"
      description: "Development environment"
    info:
      title: "Tutorial Management API"
      version: "1.0"
      description: "This API exposes endpoints to manage tutorials."
      terms-of-service: "localhost"
      contact:
        name: "ndinhnguyen"
        email: "ndinhnguyen.work@gmail.com"
        url: "dev"
      license:
        name: "MIT License"
        url: "https://choosealicense.com/licenses/mit/"
